sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t travis/docker-react -f Dockerfile.dev .

scripts:
  - docker run travis/docker-react:latest npm run test -- --coverage