sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t hellomoto177/docker-react -f Dockerfile.dev .

scripts:
  - docker run hellomoto177/docker-react:latest npm run test -- --coverage